### ISSUE TITLE
Refactor Turrets

### ISSUE THREAD

**Issue by biscuitWizard** [NebulaSS13/NebulaFeatureRequests#27]
Make them actually pose a threat.

Specific notes:

1. Add a turret controller that uses the new /computer_network extensions.
2. Integrate it with the network security components.
3. Add varying degrees of lethality, up to extremely lethal and a challenge for even robust players. Right now turrets are a joke.

Loaf adds: Make it used the mounted gun code.

I'll add a bounty of 40$ for when/if the PR makes it into /dev.

**Comment by SierraKomodo** [comment]
Didn't know this existed until now but I've actually already started on a turret rework. I'll look into the specifics you're requesting as well. Details on what my original plans were are here: https://github.com/NebulaSS13/Nebula/pull/477

**Comment by biscuitWizard** [comment]
Great. When the PR is merged, send a message to me on Discord (bitMuse#0861) or here and I'll give you the bounty.

The files you'll want to look for example are "network_lock.dm" which utilizes the network access card for permissions checking. Optimally, you could make the turret control program a modular_computer program and check the network_lock on each turret to prevent unauthorised modifications.

**Comment by biscuitWizard** [comment]
Increased bounty.
