### ISSUE TITLE
Parrying expansion and tweaks

### ISSUE THREAD

**Issue by comma** [NebulaSS13/NebulaFeatureRequests#29]
Make parry mode toggleable instead of always-on. New HUD button for that.

Parrying takes stamina cost (higher if blocking heavy weapon with lighter weapon)
Parrying sets attack cooldown (or half of it)
If you have no stamina or are on attack cooldown, parrying fails.

Increased parry chance if you have attacked area selected on aim dolly.

**Comment by CrimsonShrike** [comment]
Perhaps have a button similar to sprinting too for temp toggle?
