### ISSUE TITLE
Toggleable "falls dead, their eyes dead and lifeless" message

### ISSUE THREAD

**Issue by Sebbe9123** [NebulaSS13/NebulaFeatureRequests#5]
Hello!

So! As someone that really enjoys HRP this message has always irked me as I feel like getting a popup in chat makes... little sense. To be able to see if someone is dead or not by a message in the sidebar feels a bit cheesy when you can just quickly check their pulse which takes barely three seconds.

So my idea is in the code for HRP server to just flick it off with a = 0 statement or something simple like that.
Thank you for taking it into consideration.

**Comment by MistakeNot4892** [comment]
Per Discord convo - Baycode hasn't shown a death message for awhile, but it might be nice to readd it with a config toggle for non-HRP servers who want to use it.
